import type { Config } from "tailwindcss"

const config: Config = {
  content: ["./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        background: "#fff8f5",
        surface: "#fff8f5",
        "surface-bright": "#fff8f5",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#fcf2eb",
        "surface-container": "#f6ece6",
        "surface-container-high": "#f0e6e0",
        "surface-variant": "#eae1da",
        "on-background": "#1f1b17",
        "on-surface": "#1f1b17",
        "on-surface-variant": "#3e4943",
        "inverse-surface": "#342f2b",
        "inverse-on-surface": "#f9efe8",
        primary: "#005d42",
        "on-primary": "#ffffff",
        "primary-container": "#047857",
        "on-primary-container": "#9ffdd3",
        "primary-fixed": "#97f5cc",
        "primary-fixed-dim": "#7bd8b1",
        "on-primary-fixed": "#002115",
        secondary: "#1b6b51",
        "secondary-container": "#a6f2d1",
        "on-secondary-container": "#237157",
        "secondary-fixed": "#a6f2d1",
        "secondary-fixed-dim": "#8bd6b6",
        "on-secondary-fixed": "#002116",
        "on-secondary-fixed-variant": "#00513b",
        tertiary: "#7d4200",
        "tertiary-fixed": "#ffdcc3",
        "on-tertiary-fixed": "#2f1500",
      },
      borderRadius: { DEFAULT: "1rem", lg: "2rem", xl: "3rem", full: "9999px" },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        margin: "2.5rem",
        "margin-mobile": "1.25rem",
      },
      fontFamily: { sans: ["var(--font-jakarta)", "system-ui", "sans-serif"] },
      fontSize: {
        display: ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["36px", { lineHeight: "44px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.03em", fontWeight: "500" }],
      },
      keyframes: {
        "pulse-soft": {
          "0%, 100%": { boxShadow: "0 0 0 0 rgba(4,120,87,0.4)" },
          "50%": { boxShadow: "0 0 0 14px rgba(4,120,87,0)" },
        },
      },
      animation: { "pulse-soft": "pulse-soft 2.5s infinite" },
    },
  },
  plugins: [],
}

export default config
